services:  
  soabus:
    image: jrgiadach/soabus:v1
    container_name: soabus
    ports:
      - "5000:5000"
    networks:
      - red
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z soabus 5000"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  servidor:
    build: ./servidor
    container_name: servidor
    depends_on:
      soabus:
        condition: service_healthy
    networks:
      - red
    restart: unless-stopped

  cliente:
    build: ./cliente
    container_name: cliente
    networks:
      - red
    restart: unless-stopped

networks:
  red:
    driver: bridge